SET SERVEROUTPUT ON;

DECLARE
    V_COUNT NUMBER;
    V_START NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_COUNT
    FROM USER_SEQUENCES
    WHERE SEQUENCE_NAME = 'SPONSORS_ID_SEQ';

    IF V_COUNT = 0 THEN
        SELECT NVL(MAX(ID), 0) + 1
        INTO V_START
        FROM SPONSORS;

        EXECUTE IMMEDIATE
            'CREATE SEQUENCE SPONSORS_ID_SEQ ' ||
            'START WITH ' || V_START || ' ' ||
            'INCREMENT BY 1 NOCACHE NOCYCLE';

        DBMS_OUTPUT.PUT_LINE('SPONSORS_ID_SEQ created.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('SPONSORS_ID_SEQ already exists.');
    END IF;
END;
/

DECLARE
    V_COUNT NUMBER;
    V_START NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_COUNT
    FROM USER_SEQUENCES
    WHERE SEQUENCE_NAME = 'EVENT_SPONSORS_ID_SEQ';

    IF V_COUNT = 0 THEN
        SELECT NVL(MAX(ID), 0) + 1
        INTO V_START
        FROM EVENT_SPONSORS;

        EXECUTE IMMEDIATE
            'CREATE SEQUENCE EVENT_SPONSORS_ID_SEQ ' ||
            'START WITH ' || V_START || ' ' ||
            'INCREMENT BY 1 NOCACHE NOCYCLE';

        DBMS_OUTPUT.PUT_LINE('EVENT_SPONSORS_ID_SEQ created.');
    ELSE
        DBMS_OUTPUT.PUT_LINE(
            'EVENT_SPONSORS_ID_SEQ already exists.'
        );
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_SPONSORS_ID
BEFORE INSERT ON SPONSORS
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
    :NEW.ID := SPONSORS_ID_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_EVENT_SPONSORS_ID
BEFORE INSERT ON EVENT_SPONSORS
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
    :NEW.ID := EVENT_SPONSORS_ID_SEQ.NEXTVAL;
END;
/

SELECT
    SEQUENCE_NAME,
    MIN_VALUE,
    INCREMENT_BY,
    LAST_NUMBER
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME IN (
    'SPONSORS_ID_SEQ',
    'EVENT_SPONSORS_ID_SEQ'
);

SELECT
    TRIGGER_NAME,
    TABLE_NAME,
    STATUS
FROM USER_TRIGGERS
WHERE TRIGGER_NAME IN (
    'TRG_SPONSORS_ID',
    'TRG_EVENT_SPONSORS_ID'
);