SET SQLBLANKLINES ON
SET DEFINE OFF

CREATE OR REPLACE TRIGGER TRG_CLUB_MEMBERSHIP_VALIDATE
BEFORE INSERT OR UPDATE
ON CLUB_MEMBERSHIPS
FOR EACH ROW
BEGIN
    :NEW.MEMBER_ROLE :=
        LOWER(TRIM(:NEW.MEMBER_ROLE));

    IF INSERTING THEN
        IF :NEW.JOINED_AT IS NULL THEN
            :NEW.JOINED_AT := SYSDATE;
        END IF;

        IF :NEW.CREATED_AT IS NULL THEN
            :NEW.CREATED_AT := SYSTIMESTAMP;
        END IF;
    END IF;

    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

SHOW ERRORS TRIGGER TRG_CLUB_MEMBERSHIP_VALIDATE