SET SQLBLANKLINES ON
SET DEFINE OFF

CREATE OR REPLACE TRIGGER TRG_NOTIFICATION_VALIDATE
BEFORE INSERT OR UPDATE
ON NOTIFICATIONS
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.CREATED_AT IS NULL THEN
            :NEW.CREATED_AT := SYSTIMESTAMP;
        END IF;
    END IF;

    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

SHOW ERRORS TRIGGER TRG_NOTIFICATION_VALIDATE