SET DEFINE OFF
SET SQLBLANKLINES ON

CREATE OR REPLACE TRIGGER TRG_EVENT_SPONSOR_VALIDATE
BEFORE INSERT OR UPDATE
ON EVENT_SPONSORS
FOR EACH ROW
BEGIN
    :NEW.STATUS := LOWER(TRIM(:NEW.STATUS));
    :NEW.CONTRIBUTION_TYPE :=
        LOWER(TRIM(:NEW.CONTRIBUTION_TYPE));

    IF :NEW.AMOUNT < 0 THEN
        RAISE_APPLICATION_ERROR(
            -20010,
            'Sponsorship amount cannot be negative.'
        );
    END IF;

    IF INSERTING THEN
        IF :NEW.AGREEMENT_DATE IS NULL THEN
            :NEW.AGREEMENT_DATE := SYSTIMESTAMP;
        END IF;

        IF :NEW.CREATED_AT IS NULL THEN
            :NEW.CREATED_AT := SYSTIMESTAMP;
        END IF;
    END IF;

    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

SHOW ERRORS TRIGGER TRG_EVENT_SPONSOR_VALIDATE