-- Overall sponsor ranking
SELECT
    S.ID,
    S.NAME,
    SUM(ES.AMOUNT) AS TOTAL_CONTRIBUTION,
    DENSE_RANK() OVER (
        ORDER BY SUM(ES.AMOUNT) DESC
    ) AS SPONSOR_RANK
FROM SPONSORS S
JOIN EVENT_SPONSORS ES
    ON S.ID = ES.SPONSOR_ID
WHERE ES.STATUS <> 'cancelled'
GROUP BY S.ID, S.NAME
ORDER BY SPONSOR_RANK;


-- Ranking inside every event
SELECT
    E.TITLE,
    S.NAME,
    ES.AMOUNT,
    DENSE_RANK() OVER (
        PARTITION BY ES.EVENT_ID
        ORDER BY ES.AMOUNT DESC
    ) AS EVENT_RANK
FROM EVENT_SPONSORS ES
JOIN EVENTS E
    ON ES.EVENT_ID = E.ID
JOIN SPONSORS S
    ON ES.SPONSOR_ID = S.ID
ORDER BY E.TITLE, EVENT_RANK;


-- Running total
SELECT
    EVENT_ID,
    SPONSOR_ID,
    AMOUNT,
    SUM(AMOUNT) OVER (
        PARTITION BY EVENT_ID
        ORDER BY AMOUNT DESC, ID
    ) AS RUNNING_TOTAL
FROM EVENT_SPONSORS
ORDER BY EVENT_ID, AMOUNT DESC;


-- Top three sponsors for each event
SELECT *
FROM
(
    SELECT
        E.TITLE AS EVENT_TITLE,
        S.NAME AS SPONSOR_NAME,
        ES.AMOUNT,
        DENSE_RANK() OVER (
            PARTITION BY ES.EVENT_ID
            ORDER BY ES.AMOUNT DESC
        ) AS CONTRIBUTION_RANK
    FROM EVENT_SPONSORS ES
    JOIN EVENTS E
        ON ES.EVENT_ID = E.ID
    JOIN SPONSORS S
        ON ES.SPONSOR_ID = S.ID
)
WHERE CONTRIBUTION_RANK <= 3
ORDER BY EVENT_TITLE, CONTRIBUTION_RANK;
