SET SQLBLANKLINES ON
SET DEFINE OFF

CREATE OR REPLACE FUNCTION FN_EVENT_FINANCIAL_HEALTH
(
    P_EVENT_ID NUMBER
)
RETURN VARCHAR2
IS
    V_HEALTH VARCHAR2(30);
BEGIN
    SELECT FINANCIAL_HEALTH
    INTO V_HEALTH
    FROM VW_REPORT_EVENT_FINANCE
    WHERE EVENT_ID = P_EVENT_ID;

    RETURN V_HEALTH;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'EVENT_NOT_FOUND';
END;
/

SHOW ERRORS FUNCTION FN_EVENT_FINANCIAL_HEALTH