CREATE OR REPLACE FUNCTION FN_EVENT_SPONSORSHIP_TOTAL (
    P_EVENT_ID NUMBER
)
RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN
    SELECT NVL(SUM(AMOUNT), 0)
    INTO V_TOTAL
    FROM EVENT_SPONSORS
    WHERE EVENT_ID = P_EVENT_ID
      AND STATUS IN ('confirmed', 'paid');

    RETURN V_TOTAL;
END;
/