SET SQLBLANKLINES ON
SET DEFINE OFF

CREATE OR REPLACE FUNCTION
FN_USER_UNREAD_NOTIFICATION_COUNT
(
    P_USER_ID NUMBER
)
RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_TOTAL
    FROM NOTIFICATIONS
    WHERE NOTIFIABLE_ID = P_USER_ID
      AND READ_AT IS NULL;

    RETURN V_TOTAL;
END;
/

SHOW ERRORS FUNCTION
FN_USER_UNREAD_NOTIFICATION_COUNT