SET SQLBLANKLINES ON
SET DEFINE OFF

CREATE OR REPLACE FUNCTION FN_VERIFY_CERTIFICATE
(
    P_VERIFICATION_CODE VARCHAR2
)
RETURN VARCHAR2
IS
    V_STATUS CERTIFICATES.STATUS%TYPE;
BEGIN
    SELECT STATUS
    INTO V_STATUS
    FROM CERTIFICATES
    WHERE LOWER(VERIFICATION_CODE) =
          LOWER(TRIM(P_VERIFICATION_CODE));

    IF LOWER(V_STATUS) = 'issued' THEN
        RETURN 'VALID';
    END IF;

    RETURN 'REVOKED';

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'NOT_FOUND';
END;
/

SHOW ERRORS FUNCTION FN_VERIFY_CERTIFICATE