SET SQLBLANKLINES ON
SET DEFINE OFF

CREATE OR REPLACE VIEW VW_CERTIFICATE_DETAILS AS
SELECT
    C.ID,
    C.CERTIFICATE_NUMBER,
    C.VERIFICATION_CODE,
    C.CERTIFICATE_TYPE,
    C.TITLE,
    C.DESCRIPTION,
    C.STATUS,
    C.ISSUED_AT,
    C.REVOKED_AT,
    C.USER_ID,
    U.NAME AS RECIPIENT_NAME,
    U.EMAIL AS RECIPIENT_EMAIL,
    C.EVENT_ID,
    E.TITLE AS EVENT_TITLE,
    E.START_TIME,
    C.ISSUED_BY,
    IU.NAME AS ISSUED_BY_NAME,
    COUNT(*) OVER (
        PARTITION BY C.EVENT_ID
    ) AS EVENT_CERTIFICATE_COUNT,
    ROW_NUMBER() OVER (
        PARTITION BY C.EVENT_ID
        ORDER BY C.ISSUED_AT, C.ID
    ) AS EVENT_ISSUE_ORDER
FROM CERTIFICATES C
JOIN USERS U
    ON U.ID = C.USER_ID
JOIN EVENTS E
    ON E.ID = C.EVENT_ID
LEFT JOIN USERS IU
    ON IU.ID = C.ISSUED_BY;

SHOW ERRORS VIEW VW_CERTIFICATE_DETAILS