SET SQLBLANKLINES ON
SET DEFINE OFF

CREATE OR REPLACE VIEW VW_NOTIFICATION_SUMMARY AS
SELECT
    N.ID,
    N.NOTIFIABLE_ID AS USER_ID,
    U.NAME AS USER_NAME,
    U.EMAIL,
    N.TYPE,
    DBMS_LOB.SUBSTR(
        N.DATA,
        4000,
        1
    ) AS DATA_TEXT,
    N.READ_AT,
    N.CREATED_AT,
    CASE
        WHEN N.READ_AT IS NULL
        THEN 'unread'
        ELSE 'read'
    END AS READ_STATUS,
    ROW_NUMBER() OVER (
        PARTITION BY N.NOTIFIABLE_ID
        ORDER BY N.CREATED_AT DESC, N.ID
    ) AS USER_NOTIFICATION_ORDER
FROM NOTIFICATIONS N
LEFT JOIN USERS U
    ON U.ID = N.NOTIFIABLE_ID;

SHOW ERRORS VIEW VW_NOTIFICATION_SUMMARY