SET SQLBLANKLINES ON
SET DEFINE OFF

CREATE OR REPLACE VIEW VW_REPORT_EVENT_FINANCE AS
SELECT
    EVENT_ID,
    EVENT_TITLE,
    START_TIME,
    EVENT_STATUS,
    TOTAL_ALLOCATED,
    PAID_EXPENSE,
    PENDING_EXPENSE,
    PAID_REFUND,
    NET_EXPENSE,
    OTHER_INCOME,
    SPONSOR_INCOME,
    TOTAL_INCOME,
    REMAINING_BUDGET,
    UTILIZATION_PERCENTAGE,
    EXPENSE_RANK,
    CASE
        WHEN TOTAL_ALLOCATED = 0
            THEN 'NO_BUDGET'

        WHEN REMAINING_BUDGET < 0
            THEN 'OVER_BUDGET'

        WHEN UTILIZATION_PERCENTAGE >= 90
            THEN 'CRITICAL'

        WHEN UTILIZATION_PERCENTAGE >= 70
            THEN 'WARNING'

        ELSE 'HEALTHY'
    END AS FINANCIAL_HEALTH
FROM VW_EVENT_BUDGET_SUMMARY;

SHOW ERRORS VIEW VW_REPORT_EVENT_FINANCE