SET SQLBLANKLINES ON
SET DEFINE OFF

CREATE OR REPLACE VIEW VW_REPORT_USER_ACTIVITY AS
WITH MEMBERSHIP_DATA AS
(
    SELECT
        USER_ID,
        COUNT(*) AS CLUB_COUNT
    FROM CLUB_MEMBERSHIPS
    GROUP BY USER_ID
),
CERTIFICATE_DATA AS
(
    SELECT
        USER_ID,
        COUNT(*) AS CERTIFICATE_COUNT,
        SUM(
            CASE
                WHEN LOWER(STATUS) = 'issued'
                THEN 1
                ELSE 0
            END
        ) AS VALID_CERTIFICATE_COUNT
    FROM CERTIFICATES
    GROUP BY USER_ID
),
NOTIFICATION_DATA AS
(
    SELECT
        NOTIFIABLE_ID AS USER_ID,
        COUNT(*) AS NOTIFICATION_COUNT,
        SUM(
            CASE
                WHEN READ_AT IS NULL
                THEN 1
                ELSE 0
            END
        ) AS UNREAD_NOTIFICATION_COUNT
    FROM NOTIFICATIONS
    GROUP BY NOTIFIABLE_ID
)
SELECT
    U.ID AS USER_ID,
    U.NAME AS USER_NAME,
    U.EMAIL,
    R.DISPLAY_NAME AS ROLE_NAME,
    U.ENGAGEMENT_POINTS,

    NVL(
        M.CLUB_COUNT,
        0
    ) AS CLUB_COUNT,

    NVL(
        C.CERTIFICATE_COUNT,
        0
    ) AS CERTIFICATE_COUNT,

    NVL(
        C.VALID_CERTIFICATE_COUNT,
        0
    ) AS VALID_CERTIFICATE_COUNT,

    NVL(
        N.NOTIFICATION_COUNT,
        0
    ) AS NOTIFICATION_COUNT,

    NVL(
        N.UNREAD_NOTIFICATION_COUNT,
        0
    ) AS UNREAD_NOTIFICATION_COUNT,

    DENSE_RANK() OVER
    (
        ORDER BY U.ENGAGEMENT_POINTS DESC
    ) AS ENGAGEMENT_RANK,

    ROW_NUMBER() OVER
    (
        PARTITION BY U.ROLE_ID
        ORDER BY
            U.ENGAGEMENT_POINTS DESC,
            U.ID
    ) AS ROLE_POSITION

FROM USERS U

LEFT JOIN ROLES R
    ON R.ID = U.ROLE_ID

LEFT JOIN MEMBERSHIP_DATA M
    ON M.USER_ID = U.ID

LEFT JOIN CERTIFICATE_DATA C
    ON C.USER_ID = U.ID

LEFT JOIN NOTIFICATION_DATA N
    ON N.USER_ID = U.ID;

SHOW ERRORS VIEW VW_REPORT_USER_ACTIVITY