SET SQLBLANKLINES ON
SET DEFINE OFF

CREATE OR REPLACE VIEW VW_SPONSORSHIP_SUMMARY AS
SELECT
    ES.ID,
    ES.EVENT_ID,
    E.TITLE AS EVENT_TITLE,
    E.START_TIME,
    ES.SPONSOR_ID,
    S.NAME AS SPONSOR_NAME,
    S.SPONSOR_TYPE,
    ES.AMOUNT,
    ES.CONTRIBUTION_TYPE,
    ES.STATUS,
    ES.AGREEMENT_DATE,
    SUM(
        CASE
            WHEN LOWER(ES.STATUS) <> 'cancelled'
            THEN ES.AMOUNT
            ELSE 0
        END
    ) OVER (
        PARTITION BY ES.EVENT_ID
    ) AS EVENT_TOTAL,
    DENSE_RANK() OVER (
        PARTITION BY ES.EVENT_ID
        ORDER BY ES.AMOUNT DESC
    ) AS EVENT_CONTRIBUTION_RANK
FROM EVENT_SPONSORS ES
JOIN EVENTS E
    ON ES.EVENT_ID = E.ID
JOIN SPONSORS S
    ON ES.SPONSOR_ID = S.ID;

SHOW ERRORS VIEW VW_SPONSORSHIP_SUMMARY