SET SQLBLANKLINES ON
SET DEFINE OFF

CREATE OR REPLACE VIEW VW_USER_ENGAGEMENT_SUMMARY AS
SELECT
    U.ID AS USER_ID,
    U.NAME AS USER_NAME,
    U.EMAIL,
    U.ENGAGEMENT_POINTS,
    R.NAME AS ROLE_NAME,
    R.DISPLAY_NAME AS ROLE_DISPLAY_NAME,
    COUNT(DISTINCT CM.ID) AS CLUB_COUNT,
    DENSE_RANK() OVER (
        ORDER BY U.ENGAGEMENT_POINTS DESC
    ) AS ENGAGEMENT_RANK,
    ROW_NUMBER() OVER (
        PARTITION BY U.ROLE_ID
        ORDER BY U.ENGAGEMENT_POINTS DESC, U.ID
    ) AS ROLE_POSITION
FROM USERS U
LEFT JOIN ROLES R
    ON R.ID = U.ROLE_ID
LEFT JOIN CLUB_MEMBERSHIPS CM
    ON CM.USER_ID = U.ID
GROUP BY
    U.ID,
    U.NAME,
    U.EMAIL,
    U.ENGAGEMENT_POINTS,
    U.ROLE_ID,
    R.NAME,
    R.DISPLAY_NAME;

SHOW ERRORS VIEW VW_USER_ENGAGEMENT_SUMMARY